### PR TITLE
Add nested toc list

### PR DESCRIPTION
**Pull request by tobiju**
This would improve the possibilities to render the toc navigation.

### CODE REVIEW

**Comment by pmjones** [comment]
@tobiju this is marked as work-in-progress; let me know when you think it's ready!

**Comment by pmjones** [comment]
@tobiju Let me know when this goes from "work in progress" to "ready" :-)

**Comment by tobiju** [comment]
The flat toc list could now get as nested list. This is implemented via iterator interface. 
Please review carefully :). I tested it with a large documentation nested in a few books. No Problems here.

**Comment by tobiju** [comment]
@pmjones what do you think?

**Comment by pmjones** [comment]
If you're good with it, I am. Merging!

**Pull request merged**
