### PR TITLE
Add bookdown themes as composer dependency

### PR DESCRIPTION
**Pull request by tobiju**
You should add the package on packagist. I have no permissions on that project.

### CODE REVIEW

**Comment by pmjones** [comment]
I have now added bookdown/themes on Packagist. Do you want to update the PR, or shall I merge now, and let you make the change in a later PR?

**Comment by tobiju** [comment]
I would change the merge request.

**Comment by tobiju** [comment]
Could you update packagist to accept version bookdown/themes in version 1.1.2. And whats wrong with the hhvm travis-ci?

**Comment by pmjones** [comment]
Done, and set to auto-update.

For HHVM, I think Travis wants "dist: trusty".

**Comment by tobiju** [comment]
I am done for now.

**Pull request merged**
