### PR TITLE
Add index process to generate a json index file for lunr.

### PR DESCRIPTION
**Pull request by tobiju**
The index process creates a index.json file in the root of the book target. This file can then be used to implement lunr.js for search the book.

### CODE REVIEW

**Comment by pmjones** [comment]
This looks good! Do we want to call it the "index" process, or the "indexing" process? (I ask because someone might think of "index pages".)

**Comment by tobiju** [comment]
You can change that if u think this could be misunderstood.
Am 29.03.2016 16:47 schrieb "Paul M. Jones" notifications@github.com:

**Comment by pmjones** [comment]
Good enough. Merging as-is, and I reserve the right to change the name later if needed. Thanks!

**Comment by sandrokeil** [comment]
@tobiju  Awesome. :tada: 

"indexing" process sounds better for me.

**Comment by pmjones** [comment]
(/me nods) Yeah, "indexing" or "indexer." I'll get around to changing that later.

Thanks again for your good work here!

**Comment by tobiju** [comment]
Okay, you are welcome.
Am 29.03.2016 17:45 schrieb "Paul M. Jones" notifications@github.com:

**Pull request merged**
