### PR TITLE
Add bookdown/themes as submodule and default theme

### PR DESCRIPTION
**Pull request by tobiju**
First Step to include bookdown/themes to bookdown/bookdown project as default theme. @pmjones would you like to rebase your master and development branch to 1.x and use tags on master to publish a new version. It would be better to maintain the project on development branch.

### CODE REVIEW

**Comment by tobiju** [comment]
@pmjones: we should revert that, because UnitTests are broken. We need a up to date development branch to go further.

**Comment by pmjones** [comment]
Reverted.

Is working on 1.x especially troublesome? All the release tags currently come from that branch.

**Comment by tobiju** [comment]
Yes it is working but has breaking changes. Like the removed template folder. We should first fix the unit tests before merging. What do you think?

**Comment by pmjones** [comment]
Ah, breaking changes? Perhaps we need a 2.x branch for that, then. Thoughts?

**Comment by tobiju** [comment]
Sounds good.

**Comment by pmjones** [comment]
2.x is in place -- break to your heart's content! :-)

Also, I may remove master and develop entirely, as their presence may be confusing.

**Comment by pmjones** [comment]
Say -- shouldn't the new default bookdown/themes be part of the *project* and not the *library* ?

**Comment by tobiju** [comment]
We could develop the complete theme in the bookdown project. So we do not need the library.

**Comment by pmjones** [comment]
If you're OK with it, I think that would be the way to go. The project can handle the new theme stuff without a version bump. Let me know if that turns out *not* to work, and we'll come back to the 2.x branch here instead.

Sorry for the hassle, and thanks for your patience.

**Comment by tobiju** [comment]
Yes, lets do it that way. So we remove the project bookdown/themes and implement everything in the current template. Could you create a theme branch we will work on the next time?

**Comment by pmjones** [comment]
Would we have to remove bookdown/themes? Correct me if I'm wrong here, but my thinking was:

- bookdown/project gets a new dependency in composer.json: bookdown/themes
- bookdown/project `book/bookdown.json` changes the "templates" value to point to a default bookdown theme directory that has been loaded by Composer

Then bookdown/themes can be updated independently from the project.

Does that make sense?

**Comment by tobiju** [comment]
Okay so let me correct my pull request.

**Pull request merged**
